name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.preset_image.outputs.image_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preset Image Name
        id: preset_image
        run: |
          IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7 | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_URL=${IMAGE_URL}" >> $GITHUB_ENV
          echo "::set-output name=image_url::${IMAGE_URL}"
        outputs:
          image_url: ${{ steps.preset_image.outputs.image_url }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.preset_image.outputs.image_url }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Image URL
        run: echo "${{ needs.build.outputs.image_url }}"

      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
          image: ${{ needs.build.outputs.image_url }}
